apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app2
  template:
    metadata:
      labels:
        app: flask-app2
    spec:
      containers:
      - name: flask
        image: abdelhamedreda/pyflask:v1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service2
spec:
  selector:
    app: flask-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30010
  type: NodePort